### ISSUE TITLE
Downstream test failures caused by 0.3.0

### ISSUE THREAD

**Issue by tkelman** [JuliaMath/IterativeSolvers.jl#116]
tracking issue for https://github.com/JuliaLang/METADATA.jl/pull/9190#issuecomment-301363799

- GeostatInversion https://github.com/JuliaCI/pkg.julialang.org/blob/07ab772b21a90b86b3c3cb32f48677b440b7902b/logs/GeostatInversion_0.5.log
- PyAMG https://github.com/JuliaCI/pkg.julialang.org/blob/07ab772b21a90b86b3c3cb32f48677b440b7902b/logs/PyAMG_0.5.log
- RobustLeastSquares https://github.com/JuliaCI/pkg.julialang.org/blob/07ab772b21a90b86b3c3cb32f48677b440b7902b/logs/RobustLeastSquares_0.5.log

there may actually be 2 or 3 separate bugs here, not sure

**Comment by lopezm94** [comment]
It appears to be all these errors were triggered because of the API change in `IterativeSolvers` @tkelman .

I have checked `GeostatInversion` @montyvesselinov. The default return of the solvers is the result without a `ConvergenceHistory` type,
so you just need to remove the `[1]` at the end of this [line](https://github.com/madsjulia/GeostatInversion.jl/blob/master/src/lsqr.jl#L54). If you want to use the `ConvergenceHistory` then set the log keyword value to true: `log=true`.

In the case of `PyAMG` @lukeolson, a lot of positional arguments have been moved to keywords.

I haven't check too deeply the last package but is probably due to an API change as well @andyferris.

You will find more changes in the [manual](https://juliamath.github.io/IterativeSolvers.jl/latest/). I would suggest using the help command  `?`, the new API for each function is described there in a compact way.

**Comment by lukeolson** [comment]
let me know what you need changed in PyAMG -- not sure I see the cause of the problem

**Comment by tkelman** [comment]
we're referring to the Julia wrapper package at https://github.com/cortner/PyAMG.jl by @cortner which uses this package as a test-only dependency for comparisons, PyAMG the python package has no problem here

can deprecations be added to allow any of the old style api's to keep working for now with warnings?

**Comment by lopezm94** [comment]
Whoops it makes sense now, I wasn't able to find the specific line...

**Comment by montyvesselinov** [comment]
Proposed changes above fixed: GeostatInversion. Thank you very much!


-monty
