### ISSUE TITLE
Roadmap to accepting LinearMaps as arguments

### ISSUE THREAD

**Issue by jiahao** [JuliaMath/IterativeSolvers.jl#34]
@Jutho's [LinearMaps.jl](https://github.com/Jutho/LinearMaps.jl) offers an elegant uniform interface to linear operations as represented by dense matrices, sparse matrices and functions (and possibly other things I haven't looked at yet).

It would be nice to accept `LinearMaps` as an acceptable input to the iterative algorithms here, which would eliminate checks in the algorithms for whether to apply or multiply.

Realistically I think it would make sense to simply deprecate the checks for `Function` inputs and assume that premultiplication is supported.

A wrinkle in this scheme would be how to specify preconditioning operations. Currently `M \ b` is used in code that specifies preconditioning using a matrix `M`.

**Comment by Jutho** [comment]
I haven't touched this package in a while, but I am certainly willing to implement any change necessary. 

Thanks for all the work IterativeSolvers.jl, I wish I had some more time to contribute to this. Even though most of the bugs in `eigs` now seem to be fixed, I still share your dream to get rid of ARPACK at some point.

**Comment by ChrisRackauckas** [comment]
For iterative methods, shouldn't everything be specified in terms of a function for computing `Av`, instead of the input matrix `A`? Dispatch could be used for matrix inputs to make the closure `(v) -> A*v` and then solve using this `Av` function, and it shouldn't have a noticeable cost. This would open up the API to allow people to pass in any function `f(v)` which produces `A*v`, so it would solve this problem and others like using IterativeSolvers.jl in a matrix-free way (just make `f(v)` be matrix-free).

**Comment by andreasnoack** [comment]
I don't think a `Function` argument is much more general than `LinearMap`. You can always wrap your function in a `LinearMap` but most often you probably just want to overload `A_mul_B!` directly instead of defining some update function first. Using `A_mul_B!` also provides a standard interface for in-place updates of the result vector.

**Comment by ChrisRackauckas** [comment]
I see what you're saying. Thanks for clearing that up. Yeah, functions can just be done through `FunctionMap`. 

Then yeah, taking a good look at all of this, it really seems like it should all internally use `LinearMaps`, and then the methods should just have dispatches to wrap whatever is given (function, matrix, etc.) in a linear map.

**Comment by ChrisRackauckas** [comment]
I know that @shivin9 has looked into this a bit. Can you give us an update on what the current state is? IIRC things which satisfy the LinearMaps interface have been tested to work with LSQR, CG, and GMRES? It might be good to just make a test that runs as much as possible, and see if there are any other changes required.

**Comment by Jutho** [comment]
I will update LinearMaps.jl soon (hopefully this week) to make it v0.6 ready and add some further improvements. After that, I would actually not mind to transfer ownership of LinearMaps so that it can be maintained by the community.  I am not using it myself very often and thus have no strong requirements or constraints about the future of this package. Maybe this could help in tayloring LinearMaps.jl further to become a suitable add-on for IterativeSolvers.jl.

**Comment by haampie** [comment]
Closing this since LinearMaps is compatible with IterativeSolvers (and recommended in the docs).
